# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'ComicWrap.Tests/ComicWrap.Tests.csproj'
    testRunTitle: 'Shared Test'